version: '3'

services:
    bwpm-tester:
        container_name: "bwpm-tester"
        image: romana/os-chromium-tester
        volumes:
            - ${BW_TEST_CONTAINER_DIR}/testers/os-data:/data
            - ${BW_BASE_DIR}:/tests
        environment:
            - BW_TEST_PROJECT=${BW_TEST_PROJECT}
            - BW_TEST_NET_NAME=${BW_TEST_NET_NAME}
            - BW_TEST_JOOMLA_VERSION=${BW_TEST_JOOMLA_VERSION}
            - BW_TEST_BWPM_VERSION=${BW_TEST_BWPM_VERSION}
            - BW_TEST_VM_VERSION=${BW_TEST_VM_VERSION}
            - BW_TEST_BWPM_INSTALL=${BW_TEST_BWPM_INSTALL}
            - BW_TEST_CAT=${BW_TEST_CAT}
            - BW_TEST_DEBUG=${BW_TEST_DEBUG}
            - BW_TEST_RUNNER=${BW_TEST_RUNNER}
        entrypoint: /data/bwpm_tester_start.sh
        working_dir: /tests
        networks:
            tester-net-bwpm.nil:
                ipv4_address: 172.18.0.22

networks:
    tester-net-bwpm.nil:
        external:
            name: ${BW_TEST_NET_NAME}_tester-net-bwpm.nil
