version: '2'

services:
    tester:
        container_name: "tester"
        image: romana/wheezy-cr-tester
        hostname: tester
        domainname: tester-net.nil
        volumes:
            - "/vms/dockers/containers/testers/deb-data:/data"
            - "/vms/dockers/global_data/tests/BwPostman:/tests"
        environment:
            - TEST_CAT=single
        entrypoint: /data/entrypoint.sh
        working_dir: /tests
        networks:
            tester-net.nil:
                ipv4_address: 172.18.0.10
        ports:
            - "4544:4544"
            - "5900:5900"

networks:
    tester-net.nil:
        external:
            name: infrastructure_tester-net.nil
