version: '3'

networks:
    tester-net.nil:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/24

services:
    mailer:
        container_name: "mailer"
        image: romana/os-postfix
        hostname: mailer
        domainname: tester-net.nil
        restart: always
        expose:
            - "25"
        volumes:
            - "/vms/dockers/containers/infrastructure/os_base/os_data:/outerworld"
        networks:
            tester-net.nil:
#                ipv4_address: 172.18.0.26
